### ISSUE TITLE
Not working with version 3.5.0 of Fat-Free Framework

### ISSUE THREAD

**Issue by rafamds** [rafamds/f3-error-handler#1]
This class isn't working with the new version 3.5.0 of Fat-Free Framework, have to change the way to extract trace, since they have changed the way to output them.

**Comment by Rayne** [comment]
Didn't https://github.com/rafamds/f3-error-handler/commit/b3d599a0a0e817190a657d3e42e3ef2e92f78138 fix this bug?

**Comment by rafamds** [comment]
You're right, forgot to close this. Thanks @Rayne
